pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_CREDENTIALS = credentials('docker-cred')
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'git-cred',
                url: 'https://github.com/aafak/cicd',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    ls -lrth
                    cd ./python-jenkins-argocd-k8s
                    echo 'Buid Docker Image'
                    docker build -t aafak/todo-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker login -u ${DOCKER_CREDENTIALS_USR} -p ${DOCKER_CREDENTIALS_PSW}
                    docker push aafak/todo-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'git-cred',
                url: 'https://github.com/aafak/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'git-cred', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        ls -ltrh
                        cd deploy
                        ls -ltrh
                        cat deploy.yaml
                        // sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        sed -i "s|image: aafak/todo-app:v[0-9]\+|image: aafak/todo-app:v${BUILD_NUMBER}|g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/aafak/cicd-demo-manifests-repo.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
