pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_CREDENTIALS = credentials('docker-cred')
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'git-cred',
                url: 'https://github.com/aafak/cicd',
                branch: 'main'
           }
        }

        stage('Get Git Commit Hash') {
            steps {
                script {
                    // Retrieve the latest Git commit hash
                    def commitHash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    env.COMMIT_HASH = commitHash
                    sh '''
                    echo ${COMMIT_HASH}
                    '''
                }
            }
        }

        stage('Build Docker'){
            steps{
                // Instead of using the build number, use git commit hash. because jenkins build number
                // can be reset if jenkins redeploy
                // docker build -t aafak/todo-app:${BUILD_NUMBER}
                script{
                    sh '''
                    ls -lrth
                    cd ./python-jenkins-argocd-k8s
                    echo 'Buid Docker Image'
                    docker build -t aafak/todo-app:${COMMIT_HASH} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker login -u ${DOCKER_CREDENTIALS_USR} -p ${DOCKER_CREDENTIALS_PSW}
                    docker push aafak/todo-app:${COMMIT_HASH}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'git-cred',
                url: 'https://github.com/aafak/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {

               // for build number update
               //  sed -i "s|image: aafak/todo-app:v[0-9][0-9]*|image: aafak/todo-app:v${BUILD_NUMBER}|g" deploy.yaml
                script{
                    withCredentials([usernamePassword(credentialsId: 'git-cred', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        ls -ltrh
                        cd deploy
                        ls -ltrh
                        cat deploy.yaml
                        sed -i "s|image: aafak/todo-app:[a-f0-9]*|image: aafak/todo-app:${COMMIT_HASH}|g" deploy.yaml
                        cat deploy.yaml
                        git config user.email "aafak.mitsmca09@gmail.com"
                        git config user.name "aafak"
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/aafak/cicd-demo-manifests-repo.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
